# Generated by Django 5.0.6 on 2024-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readinf_time',
            field=models.PositiveIntegerField(default=10, verbose_name='زمان مطالعه'),
            preserve_default=False,
        ),
    ]
