# Generated by Django 5.0.6 on 2024-07-24 06:17

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, scale=None, size=[500, 500], upload_to='post_images/'),
        ),
    ]
