# Generated by Django 5.0.6 on 2024-08-03 18:48

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_image_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=70,
                scale=None,
                size=[500, 500],
                upload_to="armin",
            ),
        ),
    ]
