# Generated by Django 5.0.6 on 2024-08-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_image_image_file_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="job",
            field=models.CharField(blank=True, null=True, verbose_name="شغل"),
        ),
    ]
